default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: medods_test_development

test:
  <<: *default
  database: medods_test_test

production:
  <<: *default
  database: medods_test_production
  username: medods_test
  password: <%= ENV["MEDODS_TEST_DATABASE_PASSWORD"] %>
